import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

// const inter = Inter({ subsets: ['latin'] });

const yungothic = localFont({
  src: '../../public/fonts/yungothic320.ttf',
  weight: '320',
  variable: '--font-yungothic',
});
const galmuri = localFont({
  src: '../../public/fonts/Galmuri7.ttf',
  weight: '320',
  variable: '--font-galmuri',
});

export const metadata: Metadata = {
  title: 'GYMMI',
  description: 'Generated by create next app',
  themeColor: '#1180FC',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${yungothic.variable} ${galmuri.variable}`}>
      <body>{children}</body>
    </html>
  );
}
